services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  expensereport.webapi:
    image: expensereport.webapi
    build:
      context: .
      dockerfile: ExpenseReport.WebApi/Dockerfile

